In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
from numpy import*
a=array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
from numpy import*
a=array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
