In [7]:
#Read the Data
import pandas as pd
import time #for measuring time
mat=pd.read_csv("6citytsp.csv", header=None).values

#checking

print(mat)
print(mat.dtype)

from itertools import permutations    #for generating every possible tour

mat=pd.read_csv("6citytsp.csv", header=None).values
citynames=list(range(mat.shape[0]))   #city names, for simplicity 0 to #Cities-1
per=permutations(citynames)           #generating permutations, return type is itertools.perm
print(type(per))                      #checking the type for per
print(list(per))

#print(per) #checking

import numpy as np
st=time.process_time()
besttourlength=np.inf #initially positive infinity
for tour in per:      #examining 1 tour at a time
    tourlength=0
    for i in range(len(tour)-1):
        tourlength+=mat[tour[i], tour[i+1]]
    tourlength+=mat[tour[i+1],tour[0]]
    if tourlength<besttourlength:   #minimum logic
        besttourlength=tourlength
        besttour=tour

et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour: ", besttour)
print("Best Tour's Length: ", besttourlength)
print("Time Taken: ", time_taken_ms)

[[  0  64 378 519 434 200]
 [ 64   0 318 455 375 164]
 [378 318   0 170 265 344]
 [519 455 170   0 223 428]
 [434 375 265 223   0 273]
 [200 164 344 428 273   0]]
int64
<class 'itertools.permutations'>
[(0, 1, 2, 3, 4, 5), (0, 1, 2, 3, 5, 4), (0, 1, 2, 4, 3, 5), (0, 1, 2, 4, 5, 3), (0, 1, 2, 5, 3, 4), (0, 1, 2, 5, 4, 3), (0, 1, 3, 2, 4, 5), (0, 1, 3, 2, 5, 4), (0, 1, 3, 4, 2, 5), (0, 1, 3, 4, 5, 2), (0, 1, 3, 5, 2, 4), (0, 1, 3, 5, 4, 2), (0, 1, 4, 2, 3, 5), (0, 1, 4, 2, 5, 3), (0, 1, 4, 3, 2, 5), (0, 1, 4, 3, 5, 2), (0, 1, 4, 5, 2, 3), (0, 1, 4, 5, 3, 2), (0, 1, 5, 2, 3, 4), (0, 1, 5, 2, 4, 3), (0, 1, 5, 3, 2, 4), (0, 1, 5, 3, 4, 2), (0, 1, 5, 4, 2, 3), (0, 1, 5, 4, 3, 2), (0, 2, 1, 3, 4, 5), (0, 2, 1, 3, 5, 4), (0, 2, 1, 4, 3, 5), (0, 2, 1, 4, 5, 3), (0, 2, 1, 5, 3, 4), (0, 2, 1, 5, 4, 3), (0, 2, 3, 1, 4, 5), (0, 2, 3, 1, 5, 4), (0, 2, 3, 4, 1, 5), (0, 2, 3, 4, 5, 1), (0, 2, 3, 5, 1, 4), (0, 2, 3, 5, 4, 1), (0, 2, 4, 1, 3, 5), (0, 2, 4, 1, 5, 3), (0, 2, 4, 3, 1, 5), (0, 2, 4, 3, 5, 1

In [8]:
import time
mat=pd.read_csv("6citytsp.csv", header=None).values
#checking
print(mat)
#asking for starting city
startcity=int(input("Enter the start city from 0 to "+ str(mat.shape[0]-1)+ " "))
#generating city names
citynames=list(range(mat.shape[0]))
#removing the starting city
citynames.remove(startcity) #startcity is scanned, so, we need to generate permutations
#generating permutations
per=list(permutations(citynames))
#print(per)

st=time.process_time()
besttourlength=np.inf
for tour in per:
    tourlength=0
    for i in range(len(tour)-1):
        tourlength+=mat[tour[i], tour[i+1]]
tourlength+=mat[tour[i+1], startcity] #lastcity to startcity
tourlength+=mat[startcity, tour[0]] #startcity to actual city
if tourlength < besttourlength: #minimum logic
    besttourlength=tourlength
    besttour=tour

besttour=list(besttour)
besttour.insert(0,startcity)
et=time.process_time()
time_taken_ms=(et-st)*1000
print("Best Tour: ", besttour)
print("Best Tour's Length", besttourlength)
print("Time Taken: ", time_taken_ms)

[[  0  64 378 519 434 200]
 [ 64   0 318 455 375 164]
 [378 318   0 170 265 344]
 [519 455 170   0 223 428]
 [434 375 265 223   0 273]
 [200 164 344 428 273   0]]


Enter the start city from 0 to 5  2


Best Tour:  [2, 5, 4, 3, 1, 0]
Best Tour's Length 1737
Time Taken:  0.8930000000049176


In [10]:
#read the data
import pandas as pd
import numpy as np
import time
mat=pd.read_csv("6citytsp.csv",header=None).values.astype(float)
#asking for the startcity
startcity=int(input("Enter the Start City from 0 to " + str(mat.shape[0]-1) + ":"))
st=time.process_time()
tourlength=0
besttour=[startcity] 
mat[mat==0]=np.inf
print(mat)
matorigcopy=mat.copy()
for i in range(mat.shape[0]-1):
    if i==0:
        tourlength+=min(mat[startcity, :])
        nextbestind=np.argmin(mat[startcity, :])
        besttour.append(nextbestind)
        mat[:, nextbestind]=np.inf
        mat[:, startcity]=np.inf
    else:
        tourlength+=min(mat[nextbestind,:])
        nextbestind=np.argmin(mat[nextbestind,:])
        mat[:,nextbestind]=np.inf #can't visit again
        besttour.append(nextbestind)

    tourlength+=matorigcopy[nextbestind,startcity]
    et=time.process=(et-st)*1000
    

print("Best Tour: ", besttour)
print("Best Tour's Length", besttourlength)
print("Time Taken: ", time_taken_ms)

Enter the Start City from 0 to 5: 3


[[ inf  64. 378. 519. 434. 200.]
 [ 64.  inf 318. 455. 375. 164.]
 [378. 318.  inf 170. 265. 344.]
 [519. 455. 170.  inf 223. 428.]
 [434. 375. 265. 223.  inf 273.]
 [200. 164. 344. 428. 273.  inf]]
Best Tour:  [3, np.int64(2), np.int64(4), np.int64(5), np.int64(1), np.int64(0)]
Best Tour's Length 1737
Time Taken:  0.8930000000049176
